### ISSUE TITLE
Criar pipeline de deploy

### ISSUE THREAD

**Issue by gustapinto** [gustapinto/fatec_dsm_pi_quarto_semestre#20]

**Comment by luigieai** [comment]
Opa, sou fatecano ja formado e trampo na área de infra/devops, aceitam contribuições para esse projeto? Fico a disposição

tmj

**Comment by gustapinto** [comment]
Oba, obrigadão pelo interesse em contribuir!

No momento não estamos aceitando contribuições por conta de se tratar de um projeto que estamos desenvolvendo para o curso (aka. nota kkkkk), mas esperamos poder abrir o projeto para toda a comunidade ao final do semestre!
